name: Installs all the dependencies and toolchains required
description: Runs the setup process required for the Stream Signer crates
inputs:
  components:
    description: The components to use for the toolchain
    required: false


runs:
  using: composite
  steps:
    - name: Install extras
      run: sudo apt install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav libgstrtspserver-1.0-dev libges-1.0-dev libglib2.0-dev libgtk-3-dev
      shell: sh

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: ${{ inputs.components }}
